server:
  port: 1997

spring:
  artemis:
    mode: embedded
    broker-url: tcp://localhost:61616
    user: dev
    password: dev
    embedded:
      enabled: true
      data-directory: data/mq
      persistent: true
      queues: ares-messages,refined-messages

  jms:
    template:
      default-destination: unused
      qos-enabled: true
      delivery-mode: persistent

logging:
  level:
    org.apache.activemq.audit.base: WARN
    org.apache.activemq.autit.message: WARN
