server:
  port: 1998

alphatimer:
  queue: ares-messages
  lanes: 8

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/heats
    username: sa
    password: sa

  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true

    hibernate:
      ddl-auto: update

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: dev
    password: dev

  jms:
    template:
      default-destination: ares-messages

  mustache:
    check-template-location: false

logging:
  level:
    org.atmosphere: warn
