server:
  port: 1999

alphatimer:
  competitionKey:
  serialPort:
  storagePath: data
  serialConfiguration: ARES21
  queue: ares-messages


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/messages
    username: sa
    password: sa

  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true

    hibernate:
      ddl-auto: update

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: dev
    password: dev

  jms:
    template:
      default-destination: ares-messages
