server:
  port: 1999

alphatimer:
  competitionKey:
  serialPort:
  storagePath: data
  serialConfiguration: ARES21

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

  jpa:
    show-sql: false
    open-in-view: false
