server:
  port: 1999

alphatimer:
  storagePath: data
  queues:
    refined: refined-messages
  serial:
    tcp:
      server:
      port: 8585

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/messages
    username: sa
    password: sa

  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: dev
    password: dev

  jms:
    template:
      default-destination: refined-messages
      delivery-mode: persistent
      qos-enabled: true
      time-to-live: 36000
    pub-sub-domain: false
